"""baseline year specific figures

Revision ID: 4a753dad3902
Revises: 8eddc69d44d1
Create Date: 2026-07-19 07:20:45.605543

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4a753dad3902'
down_revision: str | None = '8eddc69d44d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: the table already has rows (real
    # baseline data), and NOT NULL columns need a value for them too.
    with op.batch_alter_table('runner_baselines', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('dx_count_this_year', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('km_this_year', sa.Float(), nullable=False, server_default='0')
        )
        batch_op.add_column(sa.Column('baseline_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runner_baselines', schema=None) as batch_op:
        batch_op.drop_column('baseline_year')
        batch_op.drop_column('km_this_year')
        batch_op.drop_column('dx_count_this_year')

    # ### end Alembic commands ###
