"""baseline first run date

Revision ID: 8eddc69d44d1
Revises: e8bf57607afb
Create Date: 2026-07-18 16:21:27.529162

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8eddc69d44d1'
down_revision: str | None = 'e8bf57607afb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runner_baselines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_run_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runner_baselines', schema=None) as batch_op:
        batch_op.drop_column('first_run_date')

    # ### end Alembic commands ###
