"""add running_club and prior_experience to users

Revision ID: 90d2960b6eea
Revises: 4a753dad3902
Create Date: 2026-07-20 11:22:54.551927

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '90d2960b6eea'
down_revision: str | None = '4a753dad3902'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('running_club', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('prior_experience', sa.Enum('never', 'once', 'multiple', name='priorexperience', native_enum=False, length=20), nullable=True))

    # ### end Alembic commands ###

    # Every account that already exists at the moment this ships is presumed
    # to have run with the community before — the self-report question is
    # only ever shown to accounts created after this point (see
    # User.prior_experience / product decision in-session). Left NULL, a
    # pre-existing account would otherwise look "unanswered" and get
    # incorrectly asked a question that doesn't apply to them.
    op.execute("UPDATE users SET prior_experience = 'multiple'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('prior_experience')
        batch_op.drop_column('running_club')

    # ### end Alembic commands ###
