"""guest users and claims

Revision ID: 9359b13eb026
Revises: cad8412b864f
Create Date: 2026-07-10 13:27:23.382591

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9359b13eb026'
down_revision: str | None = 'cad8412b864f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_user_id', sa.Integer(), nullable=False),
    sa.Column('claimant_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='claimstatus', native_enum=False, length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claimant_user_id'], ['users.id'], name=op.f('fk_guest_claims_claimant_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_user_id'], ['users.id'], name=op.f('fk_guest_claims_guest_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_claims'))
    )
    with op.batch_alter_table('guest_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_claims_claimant_user_id'), ['claimant_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_claims_guest_user_id'), ['guest_user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default backfills existing rows (real users, not guests) so the
        # NOT NULL add doesn't fail against data already in the table.
        batch_op.add_column(
            sa.Column('is_guest', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('merged_into_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_merged_into_id_users'), 'users', ['merged_into_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        # Drop the server_default after backfill — new inserts always pass the
        # value explicitly (SQLAlchemy model default), no need to keep it in the DB.
        batch_op.alter_column('is_guest', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_merged_into_id_users'), type_='foreignkey')
        batch_op.drop_column('merged_into_id')
        batch_op.drop_column('is_guest')

    with op.batch_alter_table('guest_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_claims_guest_user_id'))
        batch_op.drop_index(batch_op.f('ix_guest_claims_claimant_user_id'))

    op.drop_table('guest_claims')
    # ### end Alembic commands ###
