"""runner baseline stats

Revision ID: a6cbd931b5e8
Revises: e5f9b3d7a2c1
Create Date: 2026-07-17 07:22:42.974306

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a6cbd931b5e8'
down_revision: str | None = 'e5f9b3d7a2c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runner_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=False),
    sa.Column('dx_count', sa.Integer(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('total_km', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['runner_id'], ['users.id'], name=op.f('fk_runner_baselines_runner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runner_baselines'))
    )
    with op.batch_alter_table('runner_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runner_baselines_runner_id'), ['runner_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runner_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runner_baselines_runner_id'))

    op.drop_table('runner_baselines')
    # ### end Alembic commands ###
