"""initial schema

Revision ID: cad8412b864f
Revises: 
Create Date: 2026-07-09 15:26:51.372823

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cad8412b864f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('runner', 'organizer', 'admin', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender', native_enum=False, length=20), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_events_created_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_date'), ['date'], unique=False)

    op.create_table('event_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_photos_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_event_photos_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_photos'))
    )
    with op.batch_alter_table('event_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_photos_event_id'), ['event_id'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pace_min', sa.String(length=20), nullable=True),
    sa.Column('pace_max', sa.String(length=20), nullable=True),
    sa.Column('target_distance_km', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('route_gpx', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_groups_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_event_id'), ['event_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(length=255), nullable=False),
    sa.Column('raw_email', sa.String(length=255), nullable=True),
    sa.Column('raw_phone', sa.String(length=40), nullable=True),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('finish_status', sa.Enum('finished', 'dnf', name='finishstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_attendance_records_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_id'], ['users.id'], name=op.f('fk_attendance_records_runner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records'))
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_runner_id'), ['runner_id'], unique=False)

    op.create_table('signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_signups_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_id'], ['users.id'], name=op.f('fk_signups_runner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signups')),
    sa.UniqueConstraint('runner_id', 'group_id', name='uq_signup_runner_group')
    )
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signups_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signups_runner_id'), ['runner_id'], unique=False)

    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_record_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('pace_seconds_per_km', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('file', 'manual', name='resultsource', native_enum=False, length=20), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('track_points', sa.JSON(), nullable=True),
    sa.Column('elevation_profile', sa.JSON(), nullable=True),
    sa.Column('telemetry', sa.JSON(), nullable=True),
    sa.Column('finish_status', sa.Enum('finished', 'dnf', name='finishstatus', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', name='moderationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], name=op.f('fk_results_attendance_record_id_attendance_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results'))
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_results_attendance_record_id'), ['attendance_record_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_attendance_record_id'))

    op.drop_table('results')
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signups_runner_id'))
        batch_op.drop_index(batch_op.f('ix_signups_group_id'))

    op.drop_table('signups')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_runner_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_group_id'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_event_id'))

    op.drop_table('groups')
    with op.batch_alter_table('event_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_photos_event_id'))

    op.drop_table('event_photos')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_date'))

    op.drop_table('events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
