"""group start coordinates

Revision ID: e8bf57607afb
Revises: a6cbd931b5e8
Create Date: 2026-07-18 09:37:22.687755

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e8bf57607afb'
down_revision: str | None = 'a6cbd931b5e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('start_lng')
        batch_op.drop_column('start_lat')

    # ### end Alembic commands ###
