"""add survey system

Revision ID: fced7e74d152
Revises: 90d2960b6eea
Create Date: 2026-07-20 12:20:28.434823

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fced7e74d152'
down_revision: str | None = '90d2960b6eea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required_for_access', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_surveys_created_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveys'))
    )
    op.create_table('survey_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('long_text', 'short_text', 'single_choice', 'multi_choice', name='surveyquestiontype', native_enum=False, length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_questions_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_questions'))
    )
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_questions_survey_id'), ['survey_id'], unique=False)

    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['runner_id'], ['users.id'], name=op.f('fk_survey_responses_runner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_responses_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_responses')),
    sa.UniqueConstraint('survey_id', 'runner_id', name='uq_survey_response_runner')
    )
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_responses_runner_id'), ['runner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_responses_survey_id'), ['survey_id'], unique=False)

    op.create_table('survey_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], name=op.f('fk_survey_answers_question_id_survey_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['survey_responses.id'], name=op.f('fk_survey_answers_response_id_survey_responses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_answers')),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_survey_answer_question')
    )
    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_answers_response_id'), ['response_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_answers_response_id'))

    op.drop_table('survey_answers')
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_responses_survey_id'))
        batch_op.drop_index(batch_op.f('ix_survey_responses_runner_id'))

    op.drop_table('survey_responses')
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_questions_survey_id'))

    op.drop_table('survey_questions')
    op.drop_table('surveys')
    # ### end Alembic commands ###
